### ISSUE TITLE
Unable to Update/Uninstall due to Manual Deletion

### ISSUE THREAD

**Issue by schlongpool** [happypandax/desktop#9]
Wanting to update, I deleted all the desktop client files then downloaded the installer. The installer states "There is already a per-user installation. Will reinstall/upgrade." Upon attempting to do so it states "Installation Aborted. Setup was not completed successfully." I then tried to uninstall using Windows' "Add or Remove Programs" but could not uninstall because it points to an uninstaller that no longer exists. I also attempted the "Anyone who uses this computer" installation option which states a "Fresh install for all users," but the same problem occurs.

**Comment by twiddli** [comment]
are you on windows? try looking in your `C:\Users\Username\AppData\Local` or `C:\Users\Pew\AppData\Roaming` folder for any leftovers?

**Comment by schlongpool** [comment]
I no longer have the problem because I used ccleaner to remove the registry. Ideally, the installer shouldn't have this problem, but that's up to you. Thanks for the support and for making happypandax!
